#
#  ███▄ ▄███▓ ▄▄▄        ██████ ▄▄▄█████▓ ▄▄▄        █████▒ █████▒
#  ▓██▒▀█▀ ██▒▒████▄    ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██   ▒▓██   ▒
#  ▓██    ▓██░▒██  ▀█▄  ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▒████ ░▒████ ░
#  ▒██    ▒██ ░██▄▄▄▄██   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ░▓█▒  ░░▓█▒  ░
#  ▒██▒   ░██▒ ▓█   ▓██▒▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░▒█░   ░▒█░
#  ░ ▒░   ░  ░ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░ ▒ ░    ▒ ░
#  ░  ░      ░  ▒   ▒▒ ░░ ░▒  ░ ░    ░      ▒   ▒▒ ░ ░      ░
#  ░      ░     ░   ▒   ░  ░  ░    ░        ░   ▒    ░ ░    ░ ░
#  ░         ░  ░      ░                 ░  ░
#
# Welcome to MAStaff-Discord's configuration file!
# Here you can configure what you want to be displayed in the Discord webhook.
# You can also configure the webhook URL and the bot name.
# You can also configure the bot avatar.
#
# Remember to join my Discord server if you need help: https://discord.nookure.com/
#
# Discord configuration for the plugin.
StaffChat:
  # Enable or disable the webhook.
  enabled: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "{player}"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player sends a message in the staff chat.
  message: "**{player}** » {message}"
StaffJoin:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Join"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player joins the server.
  message: "**{player}** joined the server."
StaffLeave:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Leave"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player leaves the server.
  message: "**{player}** left the server."
StaffSwitch:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Switch"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player switches the server.
  message: "**{player}** switched from {previous_server} to {server}."
StaffEnable:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Enable"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player enables the staff mode.
  message: "**{player}** enabled the staff mode."
StaffDisable:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Disable"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player disables the staff mode.
  message: "**{player}** disabled the staff mode."
Freeze:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Freeze"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player freezes a player.
  message: "**{player}** froze **{target}**."
Unfreeze:
  # Enable or disable the webhook.
  enable: true
  # The webhook URL to send the messages.
  webhook: "https://discord.com/api/webhooks/1234567890/1234567890"
  # The name of the bot that will send the messages.
  name: "Staff Unfreeze"
  # The avatar of the bot that will send the messages.
  avatar: "https://minotar.net/helm/{player}/600.png"
  # The message that will be sent when a player unfreezes a player.
  message: "**{player}** unfroze **{target}**."